apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  url: https://pkgs.tailscale.com/helmcharts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: "*" 
  interval: 5m
  valuesFrom:
    - kind: Secret
      name: tailscale-auth
