apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:am2uI2aUgvfgb9KIhd7RHsmvzLGoQxIDW7OW2umNZrHQ2SOwspnimXrDJmtgyOq9+DkLjP29CHnAruuWjg==,iv:w2fv4MCiSLzxWeeCOUtjKwUcYO+XZZSVK/c7UApypLY=,tag:XupmMcyVDjCRpzHb7EowoA==,type:str]
sops:
    age:
        - recipient: age1aqegk6nl99eeu0qhmptw8q072vzansr3w8nl7q6yekqa2gt0uepqquza79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMldhSXRabkFNU2xEU0lp
            dmFvZE42cjFKdEtDenZMMUcrOXM4NkkrcUFBCmk4eDNselQrN29VT05ZVlpGajZG
            bG1wQ2tpSG9GZzV5c1BtYmp1cUFxZUEKLS0tIGJyK2Zqd29SYTd0WmJ0THlDaTRi
            VFN6K2VwTE14Sm5mck83YjB4WTR3bVEKpBNcuBwZQamZdsuq1SRzudIYCINnAkMK
            9SZUOOOwPMVD4csuxRukJRrKgovfPKDkZeAzF2gCkS2ox7lNK31PTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-26T20:58:58Z"
    mac: ENC[AES256_GCM,data:+TxGjkXDBzUyFmvSkOOB/Q0j3AWA8xGwfAThJacVo08EtZbUegZz7MM6TEYY40XSvVy7iZKDueSx1BSLZY4WmoJ7Yr4r2GHUoc5quMJfwvdZgxb145BjchqYXHMypkIwgzBUAXS4HadFzT1OTDNEF5ZWpUMJ0fmeP2BeaF5944w=,iv:xt8gJY3jP9mugX0BGpjVHW9LIrmEudLxvqhW0Yn7NsA=,tag:LQY0PoEUsB2s5Hfi++n8hA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
