apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data
  namespace: actualbudget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
