apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn-repo
  namespace: longhorn-system
spec:
  interval: 1m0s
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.9.0
  interval: 1m0s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: longhorn-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
spec:
  ingressClassName: nginx
  rules:
  - host: longhorn.lab
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
---
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:GVSjJiygxs7Z05lYL//TBz7hFemmTba57htpk6ft8iwjhDw7uxtMuVVqU9wHe97R+Xx8Mb2HNBY=,iv:CykQQ70vtl54f6OmfOM/mVKFeFiKrwPw08DQDCA0RyA=,tag:HOIbn1sWjznxCJD4fgmiqg==,type:str]
kind: Secret
metadata:
    name: longhorn-auth
    namespace: longhorn-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aqegk6nl99eeu0qhmptw8q072vzansr3w8nl7q6yekqa2gt0uepqquza79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcjZaWFFJRFRsaFh1ZCtQ
            YXd6RXI4bzBMM1Q4RktzdVF3Y2hFb2VZdlU0CjZySERTQk1vNldpd09wTlJQNWNr
            Mnk5dzI3L3BGajZkMm9IT2RidXdpU0EKLS0tIHZHSzBTdEdac3RrQk5acHhIOTRQ
            MklUM1dPNHV2aHl5cVorQzZFZG5pUVUKIZ6AFrRIQUPlNUzb0KY3rJiri8u2p3Di
            FY2Gt+72gqERQM28uf5ub3sWHRSimghcbM8Kiy/DLtUMjYEL+YtmUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T12:00:11Z"
    mac: ENC[AES256_GCM,data:hj11Y50/M5M6a3BA1uTG1Y1CPThlNwjYzRW42ira2w/PyK7fuFKJ+/kHnZFQ+1OYtdpI4zer+IjqnODerXHH324YXQw5LjelAAfcLzKiytFoaqutDb1I4AoPr+wlvpiTOuJN13Ii01adhnsgaUouoiBtflTqXzNUioV3DV8DIs8=,iv:yiFppqy3NoVKb9GssF86lq/xtGx063YzkICKcZ+9uIQ=,tag:oPQGl0aUGqPDOi9xYuOhVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
