---
apiVersion: v1
kind: Namespace
metadata:
  name: komga
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga
  namespace: komga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      containers:
        - name: komga
          image: gotson/komga:latest
          ports:
            - containerPort: 25600
          volumeMounts:
            - name: komga-data
              mountPath: /config
            - name: komga-books
              mountPath: /books
      volumes:
        - name: komga-data
          persistentVolumeClaim:
            claimName: komga-config
        - name: komga-books
          persistentVolumeClaim:
            claimName: komga-books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-config
  namespace: komga
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-books
  namespace: komga
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: komga
  namespace: komga
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: komga
  ports:
    - name: http
      port: 80
      targetPort: 25600

