apiVersion: v1
kind: Secret
metadata:
    name: db-encryption
    namespace: homarr
type: Opaque
stringData:
    db-encryption-key: ENC[AES256_GCM,data:tgOzGL7YrKvb+Cw3NrQFFObceL3vx4OP4uH2xOeYA34s+lqpOY7SJ3NBSs7HR9/T6pjrSKBI2rldhi6qN65XlA==,iv:zquFyz9mkmf3srlUMpstFJf+RrKkVUGabr8MtSuSMjo=,tag:hoGixQ0yIPPP950BAFhvxw==,type:str]
sops:
    age:
        - recipient: age1hft78zgtpjd5l4qqjkpx0uhf9jgywwzca96qlr96efkafx5eh4tsds3dc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bm5Ta2lHcUFQQnJUYWZj
            ckVxeTZPS0JrK0FaYmN4ZmlUVGZGS1F5RkdNCko1TmJGUEZ3Q3BaTHNETVFrSllL
            UjdzbnpCMTdSS0c3VVZUZHpQa2F4RDgKLS0tIEErQ1dORWpSZFlFWEZUdnI1VVRw
            eWJBSUlCSERuZlFVZy93S3MvckozOFUK1AhO4UE97KkwpQanPLAAcV9UgP1BvGlg
            me0VoWwsUBRX7Kx4URow+AgFsTI+8dZ0JnAJ4jC2aCd7KEtGQWAiRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T00:19:52Z"
    mac: ENC[AES256_GCM,data:GMatLWrWFxMlRKaafvd+E11ANsCgqXcsw8KnPkBcmIjsj++BnzirPI8ohNh6TgjxnuXmxaWv0hp6gHByoP+yQk9yMTm5fZn4n9sOrT52Z4meW2uF2GEtf3sWrgpgDul4IFZ8zMGSeBRNTh2uNl2Uv+l1XwWOFg8XvSYvIM1UOsw=,iv:K+3TopKrebMCNCvEHHSRQP3ekBGdNl/ynmQG1cr3I6M=,tag:2lSbZqhEfE0NMuKSDjRLHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
