apiVersion: ENC[AES256_GCM,data:Lwc=,iv:gTP4bsz8f6qxH4/bPQ5N94cVa6kSm4a3Jzp+Tutr1n0=,tag:g+mm0c39TE22u5yoeXDEpw==,type:str]
kind: ENC[AES256_GCM,data:gvqVyPg+,iv:PxtOh+3yOJOtd2uESN5n7JntaZXqMnqRoFfzu6gN/qM=,tag:1RHj5mUkn4GGSbk8fceaXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:e9gf53Sk7Ptuy1c=,iv:yDrofwJFD5RAbQVaLg99krxFebjfvEyBi4IN4SX72eE=,tag:zq5ESHdEpStNmXKJUhf1Og==,type:str]
    namespace: ENC[AES256_GCM,data:dEMns+J/HA==,iv:wkwcp+CXCaGXbphU7Wf03Pvc29E3hwlmNRZzLhlIHFw=,tag:KCxS8wCChC5BAoEaGUoUUw==,type:str]
type: ENC[AES256_GCM,data:trfwq8Hw,iv:C5BBdrnHlDUxwS2NvjiB1Hg5TovPlTaT82OazH3erWk=,tag:2tgUMy/+EOwT0qe0ZKc6mQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:VCH0ig==,iv:w+B3GCoQHaQv0imBASJBxJqCmxcOUXmvgrkXUi+RxkE=,tag:/azp7vVslmEcem62L7BxaQ==,type:str]
    password: ENC[AES256_GCM,data:ljfc6bZQc9I=,iv:sbW0szKX3g8PrRmdKgbmgoQv2P8MBEchD/7rz/9YTTs=,tag:KqjA1lrlJSixIQTek1pcJQ==,type:str]
sops:
    age:
        - recipient: age1hft78zgtpjd5l4qqjkpx0uhf9jgywwzca96qlr96efkafx5eh4tsds3dc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bERNRU5RaW94MzZyc25W
            SmU3eHFqMUQ0N0JJS2hWcS9QRkQyQkFKaEdRClFjclUveFdvWGVTcEhiRURSNWN6
            cWlGcHhsNFJ6dzNsR1JRT3psTHV1SlEKLS0tIEdGR1JhU3NyYnFQY3g5S085c2lq
            NlFRVUtUYmdwLzR0Q0JjaGU3MkpnTW8KWeCfW8PIKVZVIwnt/n8t6NExAqIbwz6g
            g2uUbGesfw9LwDzLQmbOavu8BBq1UDt1WARK8E9Ka27ZZP1jAGKfmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T23:47:09Z"
    mac: ENC[AES256_GCM,data:SUESNuanJgevf12vLYtR6s82V+iYmSUyHqyD9vHz68knP4NE5hccVu13a3eAeD1XlhXNohGq+8i5eUnP/XoNKEbTd6BhpyuuvLUzbI7AzBBWsNQtQicH7u8HvMeqKiIiPeo3dc0aqHMl8G3le+AsZAt2RlDfvJ0X1077E4Ngknc=,iv:M8+zSwM51SQWNl/uWjGMD+5xrElo6/wZYTnbvC5Llaw=,tag:JpM0w1wjvv5q2mww1PoTHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
