apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:nnPCqDzsi/999NBNGpdrFrU=,iv:YXfBxypUxaabkq+M/m7/YJ5+jdzfvby25JYitMV9SOg=,tag:UFhhRAQy8sL56f9jjTRf6A==,type:str]
    clientSecret: ENC[AES256_GCM,data:JsvQJk+v55GwYxMJUpzrq3jr3imakgnKngFXoChxrSHsxD7txHxSiOdRMABKEL56DF8O005qPtEHco3dCPmrVw==,iv:m9PAMlzTgdOHYjO0Fn1St4J9cEnSe69aV59tmV89oiQ=,tag:TlZfFsw3MflPth/oDDhhIA==,type:str]
sops:
    age:
        - recipient: age1hft78zgtpjd5l4qqjkpx0uhf9jgywwzca96qlr96efkafx5eh4tsds3dc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITWh3bERCaDFxSlhuR2ph
            cThNT2hQcTNpMEFoTkt0YVlpMGNOUUtqOVZZCm1mWHFxeG9ibURPSVY1V0hsR2oz
            OUhJWGRpdUJPaUtpZEdpb2lRVXRieVkKLS0tIGI1S2pjOE41UHoyQThjd20vZHFW
            dDV6VGxnV21QMERhYUZxaGVVWk4xU00K9Fz3Vjv2fSWrvb5a7kDJs27EgFHG2Siw
            B/QdjP/MndQ92Gd5oKXJI1yku1+tg1Kf5DvyHsPwfD7WBNS1zpJtag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T20:41:10Z"
    mac: ENC[AES256_GCM,data:cJEIAuxb+y6RfTU57g8nFLVKFszM2baSJ5t+Oi31UuZO2kaTjKjuK0PrRGT1F/ttNJQorXhCVu9EGma2I1VIKlKtmEgADDxgkO+vANUDHHCkJ+DGILnkXxw5aE7OOlhx7aG0gbIZTFEKyyF9uN9+riS8jZPeSEZxTC5d7GirsMw=,iv:UtdyQMGUCkOdeg59n+xZfLcwrEa5cZZPwo867tckfh8=,tag:fyEmDdli6MjZ/q/mi3+69Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
