apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:gX+IXKfbBvk2HafTjzVVNqg=,iv:LbsoFOy8BulGE1ggZiHi+bpojKUCHsALbJDFi1bjvv4=,tag:Tu2vDEa4vkhPp6Hhp1UFrQ==,type:str]
    client_secret: ENC[AES256_GCM,data:JujXlDCwlwn+wFhDhWAWc+lk2Y6J/1WTo3bnOE6xdJcs92t3O8v0QZbPDwPounJ5GistPobie/I/nuhbrRq+Iw==,iv:yMhZSxFhshurg2ZjmZXI+QSXR/YK3mT9+oAalw6ts60=,tag:UoFSW53Gw+rUmyNYnQ+FQg==,type:str]
sops:
    age:
        - recipient: age1hft78zgtpjd5l4qqjkpx0uhf9jgywwzca96qlr96efkafx5eh4tsds3dc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaTNEbDd2NXgzZnNCa3A4
            OGlhc3ozeW90NTgwRXVLM25TUnh5WmNXNlhjCnlEa0h0MzFNejZ5bXJ1YnpXMEMr
            TU9vTW5WMURCRm5UU0JTNXIxOVAvM2sKLS0tIEpmK1AvQmZ0TVVXR1Y3dTNpM1o1
            a3BEaHBqeUgwSFRSTXNWMitaUmttNmsK80fOTNWh1BPmhF8rWozIrLFLdGmbtghW
            H4vaxlE6p9wsYUDWM8LclS+EbTn5Ua9EzsiRdLLjlJaqO7lH4wXz1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T21:04:00Z"
    mac: ENC[AES256_GCM,data:0B21zlcCYEPuxelPbSh+gGtPRzwRvO99u+t0XY/oGFIkMEwPa6G3uxCZZ+56x6A2Rx92LNKxZXY/zPbCp4LV/d73qqn32Mk1aGN+l4F1eGAhvfXdJOH+lrPHbdC90FSCRcLvqI5r8XQbJl1Ce8ixP6vIhJEUeq2JqmHvjRAqfK0=,iv:OsEKshmBVP0Hgn+qPyTf2zwnNIc90hexzwVjgqr+CU4=,tag:b0zXyEFiQS8ODJ0d724yVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
